Release v1.0.3 - Encodings, README
BrendanThompson/rb-scpt pull request #14
Opened 2018-06-28 00:29 UTC by BrendanThompson

Merge of `develop` into `master` for the upcoming `v1.0.3` release.

2018-06-28 00:30 UTC, BrendanThompson commented
@zenspider can you please review this, once we have merged into `master` will create a release as per #13

2018-06-28 07:02 UTC, zenspider requested changes
Typo

2018-06-28 07:02 UTC, zenspider commented on README.md
> +All contributions to this repo are welcome, infact wanted. Please ensure that all work is done off of the `develop` branch with a PR back into master. New versions of the gem will be built from maste
"In fact"

2018-07-06 01:34 UTC, BrendanThompson commented
@zenspider fixed the typo :)

2018-07-06 20:20 UTC, zenspider approved these changes

2018-07-06 20:20 UTC, zenspider commented
DO IT!

2018-07-13 01:18 UTC, merged